src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Il y a déjà un utilisateur avec cette adresse !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="vous devez renseigner votre prénom !")
     * @Assert\Length(min="3", minMessage="Le prénom doit faire au moins {{ min }} caractères !")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="vous devez renseigner votre nom de famille !")
     * @Assert\Length(min="2", minMessage="Le nom doit faire au moins {{ min }} caractères !")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(
     *     maxSize = "4M",
     *     mimeTypes = {"image/png", "image/jpg"},
     *     mimeTypesMessage = "Merci de charger un fichier image au format PNG ou JPG"
     * )
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mobile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email2;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\ManyToOne(targetEntity=Level::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $niv;

    /**
     * @ORM\OneToMany(targetEntity=Questionnaire::class, mappedBy="createur")
     */
    private $questionnaires;

    /**
     * @ORM\OneToMany(targetEntity=Questions::class, mappedBy="createur")
     */
    private $questions;

    public function __construct()
    {
        $this->userRoles = new ArrayCollection();
        $this->questionnaires = new ArrayCollection();
        $this->questions = new ArrayCollection();
    }
    /*******************************************/
    /* Fonctions pour le HasLifecycleCallbacks */
    /*******************************************/

    /**
     * Permet d'initialiser le SLUG
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeData()
    {
        $slugify = new Slugify();
        $slug = $slugify->slugify($this->prenom . ' ' . $this->nom . ' ' . $this->email);
        // Si le slug n'existe pas ou différent
        if (empty($this->slug) || ($slug != $this->slug)) {
            // mise à jour
            $this->slug = $slug;
        }
        if (empty($this->getDateCreation())) {
            $date_create = new \DateTime('now');
            $this->setDateCreation($date_create);
        }
        // si mot de passe vide, on met par défaut "password"
        /*        if (empty($this->hash)) {
            $this->setHash("password");
        }
        */
    }
    /***************************************************/
    /* FIN des Fonctions pour le HasLifecycleCallbacks */
    /***************************************************/
    public function getFullName(): ?string
    {
        return $this->prenom . ' ' . $this->nom;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): self
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getAdresse2(): ?string
    {
        return $this->adresse2;
    }

    public function setAdresse2(?string $adresse2): self
    {
        $this->adresse2 = $adresse2;

        return $this;
    }

    public function getPostal(): ?int
    {
        return $this->postal;
    }

    public function setPostal(?int $postal): self
    {
        $this->postal = $postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email2;
    }

    public function setEmail2(?string $email2): self
    {
        $this->email2 = $email2;

        return $this;
    }
    // function pour l'interface
    public function getRoles()
    {
        // récupération des rôles de l'utilisateur
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitre();
        })->toArray();
        // Ajout du role_user pour tout le monde
        $roles[] = 'ROLE_USER';
        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }
    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    public function getNiv(): ?Level
    {
        return $this->niv;
    }

    public function setNiv(?Level $niv): self
    {
        $this->niv = $niv;

        return $this;
    }

    /**
     * @return Collection|Questionnaire[]
     */
    public function getQuestionnaires(): Collection
    {
        return $this->questionnaires;
    }

    public function addQuestionnaire(Questionnaire $questionnaire): self
    {
        if (!$this->questionnaires->contains($questionnaire)) {
            $this->questionnaires[] = $questionnaire;
            $questionnaire->setCreateur($this);
        }

        return $this;
    }

    public function removeQuestionnaire(Questionnaire $questionnaire): self
    {
        if ($this->questionnaires->contains($questionnaire)) {
            $this->questionnaires->removeElement($questionnaire);
            // set the owning side to null (unless already changed)
            if ($questionnaire->getCreateur() === $this) {
                $questionnaire->setCreateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Questions[]

templates/partials/footer.html.twig
<footer class="py-2 text-center container-fluid">
    <p>Copyright <a class="text-warning" href="http://www.optimhum.net/" target=_blank>Optim'hum</a>
     par <a class="text-warning" href="https://buldomas-lsinformatique.netlify.app/" target=_blank>Laurent Soubigou</a> Juillet 2020</p>
</footer>

templates/partials/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="logo">
        <a href="http://www.optimhum.net/" target=_blank>
            <img src="/Images/LOGO_OPTIMHUM_HD_base.gif" alt="Logo Optim'hum">
        </a>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('homepage') }}">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('theme_index') }}">Les Thèmes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('formation_index') }}">Les Formations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('module_index') }}">Les Modules</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if app.user %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                        {% if (app.user.picture is empty) %}
                            {{app.user.fullName}}
                        {% else %}
                            <img src="{{app.user.picture}}" class="avatar avatar-mini" alt="Avatar de {{app.user.fullName}}">
                            &nbsp;{{app.user.fullName}}
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                        <a href="{{ path('account_profile') }}" class="dropdown-item">Modifier mon profil</a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ path('account_loggout') }}" class="dropdown-item">Déconnexion</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ path('account_login') }}" class="nav-link">Connexion</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% for label, messages in app.flashes %}
    <div class="container">
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                <p>{{ message | raw }}
            {% endfor %}
        </div>
    </div>
{% endfor %}